In [33]:


'''
Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами 
author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].
'''

import pandas as pd
import numpy as np

authors = pd.DataFrame({'author_id':[1, 2, 3],
                       'author_name':['Тургенев', 'Чехов', 'Островский']},
                      columns=['author_id', 'author_name'])
print(authors)

book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                    'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 
                                  'Толстый и тонкий', 'Дама с собачкой',
                                  'Гроза', 'Таланты и поклонники'],
                    'price':[450, 300, 350, 500, 450, 370, 290]},
                      columns=['author_id', 'book_title', 'price'])
print(book)

'''
Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.
'''

base_df = pd.merge(authors, book, on = 'author_id', how = 'left')
print(base_df)

'''
Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.
'''

top5 = base_df.nlargest(5, 'price')
print(top5)

'''
Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. 
В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, 
максимальная и средняя цена на книги этого автора.
'''
authors_min = base_df.groupby('author_name').agg({'price':'min'})
authors_min = authors_min.rename(columns={'price':'min'})
authors_max = base_df.groupby('author_name').agg({'price':'max'})
authors_max = authors_max.rename(columns={'price':'max'})
authors_med = base_df.groupby('author_name').agg({'price':'median'})
authors_med = authors_med.rename(columns={'price':'med'})

authors_stat1 = pd.merge(authors_min, authors_max, on = 'author_name', how = 'left')
authors_stat = pd.merge(authors_stat1, authors_med, on = 'author_name', how = 'left')
print(authors_stat)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский
   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290
   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290
   author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350
             min  max    med
author_name
Островский   290  370  330.0
Тургенев     300  450  350.0
Чехов        450  500  475.0